name: Translation
description: Provide a translation for in-game strings.
title: 'Translation: '
labels:
  - enhancement
  - translation
assignees:
  - p3lim
body:
  - type: dropdown
    id: locale
    attributes:
      label: Which locale are these translations for?
      options:
        - deDE (German)
        - esES (Spanish, Spain)
        - esMX (Spanish, Mexico)
        - frFR (French)
        - itIT (Italian)
        - koKR (Korean)
        - ptBR (Portuguese, Brazil)
        - ruRU (Russian)
        - zhCN (Chinese, Simplified, PRC)
        - zhTW (Chinese, Traditional, Taiwan)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please translate each sentence below into the fields next to them.  
        It is not required to translate all of them.

        ---
# the rest is a list of strings to translate
  - type: input
    attributes:
      label: '"Automatically accept quests"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Automatically complete quests"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Automate repeatable quests"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Highlight valuable reward"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Automatically share quests"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Skip quest gossip options"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Automate gossip options"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"When to automate gossip"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Soloing"'
      description: Used in the settings, context is "when to automate while in a raid"
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Pay Darkmoon Faire teleport"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Pause mode modifier"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Hold this key to temporarily pause all automation"'
      description: Used in the settings, a description to the above string
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Reverse pause mode"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: "While the pause key is NOT held don't automate anything"
      description: Used in the settings, a description to the above string
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Block a new item by ID"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Block a new NPC by ID or target"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Block a quest by title or ID"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Item Blocklist"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"NPC Blocklist"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Quest Blocklist"'
      description: Used in the settings
      placeholder: Translation here
